# Generated by Django 2.2.4 on 2019-08-07 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20190806_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('03189363-4f49-4ebf-a925-dc9ba63364fe'), editable=False, unique=True),
        ),
    ]
