# Generated by Django 2.2.4 on 2019-08-11 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_auto_20190810_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='crawled_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('a0308c45-785b-432d-ae62-519604478495'), unique=True),
        ),
    ]
