# Generated by Django 2.2.4 on 2019-08-11 22:11

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_auto_20190811_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('ec1c0320-0696-498b-8ce7-1ed643379c76'), unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='crawled_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
